package cn.kgc.crud.dao;

import cn.kgc.crud.entity.Employee;
import cn.kgc.crud.entity.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer empid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    Employee selectByPrimaryKey(Integer empid);

    Employee selectByPrimaryKeyWith(Integer empid);
    List<Employee> selectByExampleWith(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    int updateByPrimaryKey(Employee record);
}