package cn.kgc.crud.entity;

public class Department {
    public Department(){

    }

    public Department(Integer deptid, String deptname) {
        this.deptid = deptid;
        this.deptname = deptname;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.deptId
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.deptName
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    private String deptname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.deptId
     *
     * @return the value of tbl_dept.deptId
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.deptId
     *
     * @param deptid the value for tbl_dept.deptId
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.deptName
     *
     * @return the value of tbl_dept.deptName
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.deptName
     *
     * @param deptname the value for tbl_dept.deptName
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }
}