package cn.kgc.crud.entity;

public class Employee {
    private Department department;

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Employee(){
    }
    public Employee(Integer empid, String empname, String gender, String email) {
        this.empid = empid;
        this.empname = empname;
        this.gender = gender;
        this.email = email;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.empId
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    private Integer empid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.empName
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    private String empname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.gender
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.email
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.d_id
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.empId
     *
     * @return the value of tbl_emp.empId
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.empId
     *
     * @param empid the value for tbl_emp.empId
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.empName
     *
     * @return the value of tbl_emp.empName
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.empName
     *
     * @param empname the value for tbl_emp.empName
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public void setEmpname(String empname) {
        this.empname = empname == null ? null : empname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.gender
     *
     * @return the value of tbl_emp.gender
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.gender
     *
     * @param gender the value for tbl_emp.gender
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.email
     *
     * @return the value of tbl_emp.email
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.email
     *
     * @param email the value for tbl_emp.email
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.d_id
     *
     * @return the value of tbl_emp.d_id
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.d_id
     *
     * @param dId the value for tbl_emp.d_id
     *
     * @mbg.generated Fri Mar 08 16:35:19 GMT+08:00 2019
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}